data_dir           = "/var/lib/garage/data"
db_engine          = "sqlite"
metadata_dir       = "/var/lib/garage/meta"
replication_factor = 1
rpc_bind_addr      = "[::]:3901"
rpc_public_addr    = "127.0.0.1:3901"
rpc_secret         = "78a656c569bf75a52620fa3573ecda90b52d1534fd50790ef70411e84e2333da"

[admin]
admin_token   = "YWRtaW5fdG9rZW5fbG9jYWxfZGV2XzAwMDAwMDAw"
api_bind_addr = "[::]:3903"
metrics_token = "bWV0cmljc190b2tlbl9sb2NhbF9kZXZfMDAwMDAwMDA="

[k2v_api]
api_bind_addr = "[::]:3904"

[s3_api]
api_bind_addr = "[::]:3900"
root_domain   = ".s3.garage.localhost"
s3_region     = "us-east-1"

[s3_web]
bind_addr   = "[::]:3902"
index       = "index.html"
root_domain = ".web.garage.localhost"
